import os
from setuptools import setup, find_packages
setup(
  name = 'gem',
  packages =['gem'],
  version = 'v0.1.12',
  description = 'Math library for game programming in python. ',
  author = 'Alex Marinescu',
  author_email = 'ale632007@gmail.com',
  license='BSD 2-Clause',
  url = 'https://github.com/explosiveduck/pyGameMath',
  download_url = 'https://github.com/explosiveduck/pyGameMath/releases',
  install_requires=['six'],
  keywords = ['math', 'game', 'library'],
  classifiers = [
            'Development Status :: 4 - Beta',
            'Intended Audience :: Developers',
            'Operating System :: MacOS :: MacOS X',
            'Operating System :: Microsoft :: Windows',
            'Operating System :: Unix',
            'Topic :: Scientific/Engineering :: Mathematics',
            'Topic :: Software Development :: Libraries',
            'License :: OSI Approved :: BSD License',

            'Programming Language :: Python',
            'Programming Language :: Python :: 2',
            'Programming Language :: Python :: 2.7',
            'Programming Language :: Python :: 3',
            'Programming Language :: Python :: 3.2',
            'Programming Language :: Python :: 3.3',
            'Programming Language :: Python :: 3.4',
            'Programming Language :: Python :: 3.5',
            'Programming Language :: Python :: Implementation',
            ],
)
